const BRACES_CONTENT_REGEX = /\{([^}]*)\}/;

const REGEX_ESCAPE_PATTERN = /[.*+?^${}()|[\]\\]/g;

const TRAILING_SEMICOLON = /;$/;

const UUID_DASH_REGEX = /-/g;


export { BRACES_CONTENT_REGEX, REGEX_ESCAPE_PATTERN, TRAILING_SEMICOLON, UUID_DASH_REGEX };